name: ratelimitvalidatorservices
services:
  ratelimitvalidatordb:
    image: mcr.microsoft.com/mssql/server
    
  ratelimitvalidator.api:
    image: ${DOCKER_REGISTRY-}ratelimitvalidator.api
    build:
      context: .
      dockerfile: RateLimitValidator.API/Dockerfile
    
  ratelimitvalidator.ui:
    image: ${DOCKER_REGISTRY-}ratelimitvalidator.ui
    build:
      context: ../Frontend/request-report
      dockerfile: Dockerfile