name: ratelimitvalidatorservices
services:

  ratelimitvalidatordb:
    container_name: ratelimitvalidatordb
    environment:
      - SA_PASSWORD=P123456!!
      - ACCEPT_EULA=Y
      - MSSQL_DBNAME=ratelimitvalidatordb
    restart: always
    ports:
      - 8600:1433
    networks:
      - ratelimitvalidator_network

  ratelimitvalidator.api:
    environment:
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings:DefaultConnection=Server=ratelimitvalidatordb;Database=ratelimitvalidatordb;User Id=sa;Password=P123456!!;TrustServerCertificate=True;
    ports:
      - "32760:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    depends_on:
      - ratelimitvalidatordb
    networks:
      - ratelimitvalidator_network

networks:
  ratelimitvalidator_network:
    driver: bridge